apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJVbTl0WVhKcGIxTkhNVGs1T0RwbmFIQmZiRk0xV1ZGeGREUk5Rbms1UkVjd1lrWnlXRUl4ZUhOWWVtUkdSVzFXTkdKSFZ6ZG8iCgkJfQoJfQp9
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
